### ISSUE TITLE
`ttyS0` doesn't show iex shell

### ISSUE THREAD

**Issue by pojiro** [nerves-project/nerves_system_rpi5#8]
### Environment

* Elixir version (`elixir -v`):

```
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

* Nerves environment: (`mix nerves.env --info`)

```
mix nerves.env --info
==> nerves
==> rpi5_test

Nerves environment
  MIX_TARGET:   rpi5
  MIX_ENV:      dev
```

* Additional information about your host, target hardware or environment that may help

I use nerves_system_rpi5, v0.1.0.

### Current behavior

I configured ctty with target.exs, `config :nerves, :erlinit, update_clock: true, ctty: "ttyS0"`.

hdmi display shows, 

![image](https://github.com/nerves-project/nerves_system_rpi5/assets/4096956/73d49a4a-1ea2-489d-958a-20252aa2e4e6)

but `screen /dev/ttyUSB0 115200` doesn't show nothing.
I double checked my uart cable and inserted pin. (same pin assign can work with rpi4, rpi4 shows uart iex shell.

### Expected behavior

show iex shell.

**Comment by fhunleth** [comment]
Could you try ttyAMA0? If that doesn't work, I'll look up what it should be, but on other Pi's, it's often this.

**Comment by pojiro** [comment]
I got the shell, we need to mofidy config.txt and use ttyAMA0. I will make PR soon.

![image](https://github.com/nerves-project/nerves_system_rpi5/assets/4096956/a5a9a0ab-7dfa-468a-b8bb-7e93fef7667b)
